# Generated by Django 5.2.6 on 2025-09-13 05:37

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='account_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='account_type',
            field=models.CharField(choices=[('SAV', 'Savings'), ('CUR', 'Current')], default='SAV', max_length=3),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
