# Generated by Django 5.2.6 on 2025-09-25 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='daily_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum daily spend limit for child account', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.customerprofile'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='spending_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum balance this child account can spend', max_digits=14, null=True),
        ),
    ]
