# Generated by Django 5.2.6 on 2025-09-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customerprofile_daily_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='is_terminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='termination_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
